# Generated by Django 3.0.8 on 2020-07-26 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeA', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('rg', models.IntegerField(verbose_name='RG')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('titulacao', models.IntegerField(verbose_name='Titulação')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('turmaId', models.IntegerField(verbose_name='Turma')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('duracao', models.IntegerField(verbose_name='Duração')),
                ('dataInicio', models.DateField(blank=True, null=True, verbose_name='Data Início')),
                ('dataFim', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Atividade', to='processos.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('tipo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo')),
                ('pertece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Instrutor', to='processos.Instrutor')),
            ],
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataC', models.DateField(verbose_name='Data')),
                ('presenca', models.BooleanField(default=True, verbose_name='Presente')),
                ('matAluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Matricula', to='processos.Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('telefoneA', models.IntegerField(verbose_name='Telefone')),
                ('dataNasc', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('peso', models.IntegerField(verbose_name='Peso')),
                ('dataMat', models.DateField(blank=True, null=True, verbose_name='Data da matrícula')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Turma', to='processos.Turma')),
            ],
        ),
    ]
