# Generated by Django 3.0.8 on 2020-07-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='horario',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
    ]
