# Generated by Django 3.0.8 on 2020-07-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20200725_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='instrutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='processos.Instrutor'),
            preserve_default=False,
        ),
    ]
