# Generated by Django 3.0.8 on 2020-07-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_turma_instrutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='codigo',
        ),
        migrations.AddField(
            model_name='matricula',
            name='codigoA',
            field=models.ManyToManyField(related_name='Aluno', to='processos.Aluno'),
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='turmaId',
        ),
        migrations.AddField(
            model_name='matricula',
            name='turmaId',
            field=models.ManyToManyField(related_name='T', to='processos.Turma'),
        ),
    ]
