# Generated by Django 3.0.8 on 2020-08-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_auto_20200731_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamada',
            name='matAluno',
        ),
        migrations.AddField(
            model_name='chamada',
            name='codigoA',
            field=models.ManyToManyField(related_name='Aluno', to='processos.Aluno'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='turmaId',
            field=models.ManyToManyField(related_name='T', to='processos.Turma'),
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
